# Run just one build (one operating system, one Python version)
# at merge time, so that we have an up-to-date GitHub Actions
# build status badge in README.md. This is just a check that
# nothing obviously bad has gone wrong when merging a pull request.
name: Build status
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-18.04
    steps:
      - name: Environment - checkout code
        uses: actions/checkout@master
      - name: Environment - Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 2.7
      - name: Environment - Use Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Debugging - Export environment variables
        run: export
      - name: Compile
        run: make
      - name: Test
        run: RUBICON_LIBRARY=$(pwd)/dist/librubicon.so LD_LIBRARY_PATH="$(pwd)/dist" java org.beeware.rubicon.test.Test
